# What is Numpy

NumPy is the fundamental package for scientific computing with Python. 
It is a package that provide high-performance vector, matrix and higher-dimensional data structures for Python. 
It is implemented in C and Fortran so when calculations are **vectorized**, performance is very good.

So, in a nutshell:

* a powerful Python extension for N-dimensional array
* a tool for integrating C/C++ and Fortran code
* designed for scientific computation: linear algebra and Signal Analysis

If you are a MATLAB&reg; user we recommend to read [Numpy for MATLAB Users](http://www.scipy.org/NumPy_for_Matlab_Users) and [Benefit of Open Source Python versus commercial packages](http://www.scipy.org/NumPyProConPage). 

I'm a supporter of the **Open Science Movement**, thus I humbly suggest you to take a look at the [Science Code Manifesto](http://sciencecodemanifesto.org/)

# Getting Started with Numpy Arrays

NumPy's main object is the **homogeneous** ***multidimensional array***. It is a table of elements (usually numbers), all of the same type. 

In Numpy dimensions are called **axes**. 

The number of axes is called **rank**. 

The most important attributes of an ndarray object are:

* **ndarray.ndim**     - the number of axes (dimensions) of the array. 
* **ndarray.shape**    - the dimensions of the array. For a matrix with n rows and m columns, shape will be (n,m). 
* **ndarray.size**     - the total number of elements of the array. 
* **ndarray.dtype**    - numpy.int32, numpy.int16, and numpy.float64 are some examples. 
* **ndarray.itemsize** - the size in bytes of elements of the array. For example, elements of type float64 has itemsize 8 (=64/8) 

To use `numpy` need to import the module it using of example:

In [1]:
import numpy as np  # naming import convention

### Terminology Assumption

In the `numpy` package the terminology used for vectors, matrices and higher-dimensional data sets is *array*. 

### Reference Documentation

* On the web: [http://docs.scipy.org](http://docs.scipy.org)/

* Interactive help:

If you're looking for something

In [2]:
np.info(np.array)

array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
      ndmax=0, like=None)

Create an array.

Parameters
----------
object : array_like
    An array, any object exposing the array interface, an object whose
    ``__array__`` method returns an array, or any (nested) sequence.
    If object is a scalar, a 0-dimensional array containing object is
    returned.
dtype : data-type, optional
    The desired data-type for the array. If not given, NumPy will try to use
    a default ``dtype`` that can represent the values (by applying promotion
    rules when necessary.)
copy : bool, optional
    If ``True`` (default), then the array data is copied. If ``None``,
    a copy will only be made if ``__array__`` returns a copy, if obj is
    a nested sequence, or if a copy is needed to satisfy any of the other
    requirements (``dtype``, ``order``, etc.). Note that any copy of
    the data is shallow, i.e., for arrays with object dtype, the new
    array will point to the sa

In [3]:
np.con*?

np.concat
np.concatenate
np.conj
np.conjugate
np.convolve

#### Help is your friend

Whenever in doubt, there is the `help` function to the rescue

In [4]:
# For example, try 
help(np.ndarray)

Help on class ndarray in module numpy:

class ndarray(builtins.object)
 |  ndarray(shape, dtype=None, buffer=None, offset=0, strides=None, order=None)
 |
 |  ndarray(shape, dtype=float, buffer=None, offset=0, strides=None, order=None)
 |
 |  An array object represents a multidimensional, homogeneous array
 |  of fixed-size items.  An associated data-type object describes the
 |  format of each element in the array (its byte-order, how many bytes it
 |  occupies in memory, whether it is an integer, a floating point number,
 |  or something else, etc.)
 |
 |  Arrays should be constructed using `array`, `zeros` or `empty` (refer
 |  to the See Also section below).  The parameters given here refer to
 |  a low-level method (`ndarray(...)`) for instantiating an array.
 |
 |  For more information, refer to the `numpy` module and examine the
 |  methods and attributes of an array.
 |
 |  Parameters
 |  ----------
 |  (for the __new__ method; see Notes below)
 |
 |  shape : tuple of ints
 |   

## Numpy Array Object

`NumPy` has a multidimensional array object called ndarray. It consists of two parts as follows:
   
   * The actual data
   * Some metadata describing the data
    
    
The majority of array operations leave the raw data untouched. The only aspect that changes is the metadata.

<img src="./images/ndarray_with_details.png" />

## Creating `numpy` arrays

There are a number of ways to initialize new numpy arrays, for example from

* a Python list or tuples
* using functions that are dedicated to generating numpy arrays, such as `arange`, `linspace`, etc.

### From lists

For example, to create new vector and matrix arrays from Python lists we can use the `numpy.array` function.

In [5]:
v = np.array([1,2,3,4])
v

array([1, 2, 3, 4])

In [6]:
M = np.array([[1., 2], [3.2, 4]])
M

array([[1. , 2. ],
       [3.2, 4. ]])

The `v` and `M` objects are both of the type `ndarray` that the `numpy` module provides.

In [7]:
print('Type of v: ', type(v))
print('Type of M: ', type(M))

Type of v:  <class 'numpy.ndarray'>
Type of M:  <class 'numpy.ndarray'>


The difference between the `v` and `M` arrays is only their shapes. 

To do so, we could use the `numpy.shape` function:

In [8]:
print('Shape of v: ', np.shape(v))
print('Shape of M: ', M.shape)

Shape of v:  (4,)
Shape of M:  (2, 2)


Alternatively, We can get information about the shape of an array by using the `ndarray.shape` **property** :

In [9]:
v.shape, M.shape

((4,), (2, 2))

Equivalently, we can get information about the **size** of the two `ndarrays`, namely the *total number of elements* in the array.

In [10]:
print('Size of v:', v.size)
print('Size of M:', M.size)

Size of v: 4
Size of M: 4


#### More properties of the `numpy array`

In [11]:
M.itemsize # bytes per element

8

In [12]:
M.nbytes # number of bytes

32

In [13]:
M.ndim # number of dimensions

2

In [14]:
M.dtype

dtype('float64')

## Using array-generating functions

For larger arrays it is inpractical to initialize the data manually, using explicit python lists. 

Instead we can use one of the many **functions** in `numpy` that generates arrays of different forms. 

Some of the more common are: 

* `np.arange`; 
* `np.linspace`; 
* `np.logspace`; 
* `np.mgrid`;
* `np.random.rand`;
* `np.diag`;
* `np.zeros`;
* `np.ones`;
* `np.empty`;
* `np.tile`.

### `np.arange`

In [15]:
x = np.arange(0, 10, 1) 
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [16]:
# floating point step-wise range generatation
x = np.arange(-1, 1, 0.1)  
print(x)

[-1.00000000e+00 -9.00000000e-01 -8.00000000e-01 -7.00000000e-01
 -6.00000000e-01 -5.00000000e-01 -4.00000000e-01 -3.00000000e-01
 -2.00000000e-01 -1.00000000e-01 -2.22044605e-16  1.00000000e-01
  2.00000000e-01  3.00000000e-01  4.00000000e-01  5.00000000e-01
  6.00000000e-01  7.00000000e-01  8.00000000e-01  9.00000000e-01]


### `np.linspace` and `np.logspace`

In [17]:
# using linspace, both end points **ARE included**
np.linspace(0, 10, 25)

array([ 0.        ,  0.41666667,  0.83333333,  1.25      ,  1.66666667,
        2.08333333,  2.5       ,  2.91666667,  3.33333333,  3.75      ,
        4.16666667,  4.58333333,  5.        ,  5.41666667,  5.83333333,
        6.25      ,  6.66666667,  7.08333333,  7.5       ,  7.91666667,
        8.33333333,  8.75      ,  9.16666667,  9.58333333, 10.        ])

In [18]:
np.logspace(0, np.e**2, 10, base=np.e)

array([1.00000000e+00, 2.27278564e+00, 5.16555456e+00, 1.17401982e+01,
       2.66829540e+01, 6.06446346e+01, 1.37832255e+02, 3.13263169e+02,
       7.11980032e+02, 1.61817799e+03])

### `np.random.rand` & `np.random.randn`

In [19]:
# uniform random numbers in [0,1]
np.random.rand(5,5)

array([[0.09896922, 0.99503572, 0.09066755, 0.74487681, 0.06259134],
       [0.34656131, 0.98228065, 0.81087104, 0.69971887, 0.06267142],
       [0.89753292, 0.40744666, 0.99079639, 0.01292365, 0.5699716 ],
       [0.12814201, 0.16067761, 0.23006205, 0.54749673, 0.13228755],
       [0.5840486 , 0.21255235, 0.26671991, 0.86882184, 0.80333248]])

In [20]:
# standard normal distributed random numbers
np.random.randn(5,5)

array([[ 1.2522107 ,  0.55832445,  0.5322006 ,  0.5688361 , -0.69800129],
       [ 0.70433129, -0.70455388,  0.42560633, -0.46563879,  1.7021752 ],
       [ 1.46351608, -0.18148968,  0.35658672, -0.91466114,  0.30198537],
       [-0.66732198, -0.08151089, -0.01986347,  1.03432488, -1.41809802],
       [-2.40250628,  0.04479674,  0.28148881,  0.67985975, -0.53789753]])

### `np.diag`

In [21]:
# a diagonal matrix
np.diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [22]:
# diagonal with offset from the main diagonal
np.diag([1,2,3], k=1) 

array([[0, 1, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 3],
       [0, 0, 0, 0]])

### `np.eye`

In [23]:
# a diagonal matrix with ones on the main diagonal
np.eye(3)  # 3 is the 

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### `np.zeros` and `np.ones`

In [24]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [25]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

# Exercise

***Try by yourself*** the following commands:

    np.zeros((3,4))
    np.ones((3,4))
    np.empty((2,3))
    np.eye(5)
    np.diag(np.arange(5))
    np.tile(np.array([[6, 7], [8, 9]]), (2, 2))

## So, why is it useful then?

So far the `numpy.ndarray` looks awefully much like a Python **list** (or **nested list**). 

*Why not simply use Python lists for computations instead of creating a new array type?*

There are several reasons:

* Python lists are very general. 
    - They can contain any kind of object. 
    - They are dynamically typed. 
    - They do not support mathematical functions such as matrix and dot multiplications, etc. 
    - Implementing such functions for Python lists would not be very efficient because of the dynamic typing.
    
    
* Numpy arrays are **statically typed** and **homogeneous**. 
    - The type of the elements is determined when array is created.
    
    
* Numpy arrays are memory efficient.
    - Because of the static typing, fast implementation of mathematical functions such as multiplication and addition of `numpy` arrays can be implemented in a compiled language (C and Fortran is used).

### Python Implementation

In [26]:
import numpy as np

In [27]:
L = range(1000)

In [28]:
%timeit [i**2 for i in L]

50 μs ± 3 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


### (Kind-of the same) in Numpy Code

In [29]:
a = np.arange(1000)

In [30]:
%timeit a**2

1.13 μs ± 34.1 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


### The **Wrong** way to do it

In [31]:
%timeit [element**2 for element in a]

80.7 μs ± 2.38 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


This is the wrong way to use Numpy: iterating a `ndarray` explicitly causes you to lose all the performance gain provided by Numpy. 
This is mainly due to many causes - especially caused by the fact that the `for loop` operation is performed at _Python-level_ rather than
at _C-level_ as performed internally by Numpy

## Exercises

### Simple arrays

* Create simple one and two dimensional arrays. First, redo the examples
from above. And then create your own.

* Use the functions `len`, `shape` and `ndim` on some of those arrays and
observe their output.

In [32]:
# One-dimensional array
arr_1d = np.array([1, 2, 3, 4, 5])
print(arr_1d)

[1 2 3 4 5]


In [33]:
# Two-dimensional array
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(arr_2d)

print('len:', len(arr_2d))
print('shape:', arr_2d.shape)
print('ndim:', arr_2d.ndim)

[[1 2 3]
 [4 5 6]]
len: 2
shape: (2, 3)
ndim: 2


### Creating arrays using functions

* Experiment with `arange`, `linspace`, `ones`, `zeros`, `eye` and `diag`.

* Create different kinds of arrays with random numbers.

* Try setting the seed before creating an array with random values 
    - *hint*: use `np.random.seed`

* Look at the function `np.empty`. What does it do? When might this be
useful?

In [34]:
print(np.arange(0, 10, 2))
print(np.linspace(0, 1, 5))
print(np.ones((3, 3)))
print(np.zeros((3, 3)))
print(np.eye(4))
print(np.diag([1, 2, 3, 4]))

# setting the seed makes the random numbers reproducible
np.random.seed(0)
print(np.random.rand(3, 3))

# np.empty allocates an array without initializing its values, so it
# contains whatever garbage was already in memory. It's faster than
# zeros/ones since it skips initialization -- useful when every element
# will be overwritten right after allocation anyway.
print(np.empty((2, 3)))

[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
[[0.5488135  0.71518937 0.60276338]
 [0.54488318 0.4236548  0.64589411]
 [0.43758721 0.891773   0.96366276]]
[[6.23042070e-307 4.67296746e-307 1.69121096e-306]
 [1.42417901e-306 1.42419938e-306 7.56603881e-307]]


# Basic Data Type

You may have noticed that, in some instances, array elements are
displayed with a trailing dot (e.g. `2.` vs `2`). This is due to a
difference in the data-type used:

In [35]:
a = np.array([1, 2, 3])
a.dtype

dtype('int64')

In [36]:
a = np.array([1., 2., 3.])
a.dtype

dtype('float64')

### Note

Different data-types allow us to store data more compactly in memory,
but most of the time we simply work with floating point numbers. Note
that, in the example above, NumPy auto-detects the data-type from the
input.

You can explicitly specify which data-type you want:

In [37]:
c = np.array([1, 2, 3], dtype=float)
c.dtype

dtype('float64')

The **default** data type is floating point:

In [38]:
a = np.ones((3, 3))
a.dtype

dtype('float64')

## Basic Data Types

    bool             | This stores boolean (True or False) as a bit

    inti             | This is a platform integer (normally either int32 or int64)
    int8             | This is an integer ranging from -128 to 127
    int16            | This is an integer ranging from -32768 to 32767
    int32            | This is an integer ranging from -2 ** 31 to 2 ** 31 -1
    int64            | This is an integer ranging from -2 ** 63 to 2 ** 63 -1
    
    uint8            | This is an unsigned integer ranging from 0 to 255
    uint16           | This is an unsigned integer ranging from 0 to 65535
    uint32           | This is an unsigned integer ranging from 0 to 2 ** 32 - 1
    uint64           | This is an unsigned integer ranging from 0 to 2 ** 64 - 1

    float16          | This is a half precision float with sign bit, 5 bits exponent, and 10 bits mantissa
    float32          | This is a single precision float with sign bit, 8 bits exponent, and 23 bits mantissa
    float64 or float | This is a double precision float with sign bit, 11 bits exponent, and 52 bits mantissa
    complex64        | This is a complex number represented by two 32-bit floats (real and imaginary components)
    complex128       | This is a complex number represented by two 64-bit floats (real and imaginary components)
    (or complex)


## Numerical Types and Representation

The **numerical dtype** of an array should be selected very carefully, as it directly affects the numerical representation of elements, that is: 

   * the number of **bytes used; 
   * the *numerical range*

So, then: **What happens if I try to represent a number that is Out of range?**

Let's have a go with **integers**, i.e., `int8` and `uint8`

In [39]:
x = np.zeros(4, 'int8')  # Integer ranging from -128 to 127
x

array([0, 0, 0, 0], dtype=int8)

In [40]:
x[0] = 127
x

array([127,   0,   0,   0], dtype=int8)

In [41]:
x[0] = 128
x

OverflowError: Python integer 128 out of bounds for int8

In [ ]:
x[1] = 129
x

OverflowError: Python integer 129 out of bounds for int8

In [42]:
x[2] = 257  # i.e. (128 x 2) + 1
x

OverflowError: Python integer 257 out of bounds for int8

In [43]:
ux = np.zeros(4, 'uint8')  # Integer ranging from 0 to 255
ux

array([0, 0, 0, 0], dtype=uint8)

In [44]:
ux[0] = 255
ux[1] = 256
ux[2] = 257
ux[3] = 513  # (256 x 2) + 1
ux

OverflowError: Python integer 256 out of bounds for uint8

---

# Exercises - Basic Numpy

## Ex 1. Create an array containing integers from $2$ to $2^6$

#### Hint: use Python `range` function

In [45]:
arr = np.array(range(2, 2**6 + 1))
arr

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52,
       53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64])

## 1.1 Print `ndarray` attributes and properties
(e.g. `type`, `dtype`, `shape...`) using previous on

In [46]:
print('type:', type(arr))
print('dtype:', arr.dtype)
print('shape:', arr.shape)
print('ndim:', arr.ndim)
print('size:', arr.size)

type: <class 'numpy.ndarray'>
dtype: int64
shape: (63,)
ndim: 1
size: 63


## Ex 2. Create a 3x3 Matrix array and fill it with integer numbers

In [47]:
M = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
M

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Ex3: Create a Matrix of any size and fill it with random numbers

### HInt: take a look at `numpy.random.rand`

In [48]:
R = np.random.rand(4, 4)
R

array([[0.38344152, 0.79172504, 0.52889492, 0.56804456],
       [0.92559664, 0.07103606, 0.0871293 , 0.0202184 ],
       [0.83261985, 0.77815675, 0.87001215, 0.97861834],
       [0.79915856, 0.46147936, 0.78052918, 0.11827443]])

## Array-generating Functions

## Ex 1. Create an array containing integers from $2$ to $2^6$

#### Hint: use Python `range` function

In [49]:
arr2 = np.array(range(2, 2**6 + 1))
arr2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52,
       53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64])

## 1.1 Print `ndarray` attributes and properties
(e.g. `type`, `dtype`, `shape...`) using previous on

In [50]:
print('type:', type(arr2))
print('dtype:', arr2.dtype)
print('shape:', arr2.shape)
print('ndim:', arr2.ndim)
print('size:', arr2.size)

type: <class 'numpy.ndarray'>
dtype: int64
shape: (63,)
ndim: 1
size: 63


## Ex 2. Create a 3x3 Matrix array and fill it with integer numbers

In [51]:
M2 = np.array([[9, 8, 7],
               [6, 5, 4],
               [3, 2, 1]])
M2

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

## Ex3: Create a Matrix of any size and fill it with random numbers

### HInt: take a look at `numpy.random.rand`

In [52]:
R2 = np.random.rand(5, 5)
R2

array([[0.63992102, 0.14335329, 0.94466892, 0.52184832, 0.41466194],
       [0.26455561, 0.77423369, 0.45615033, 0.56843395, 0.0187898 ],
       [0.6176355 , 0.61209572, 0.616934  , 0.94374808, 0.6818203 ],
       [0.3595079 , 0.43703195, 0.6976312 , 0.06022547, 0.66676672],
       [0.67063787, 0.21038256, 0.1289263 , 0.31542835, 0.36371077]])

---

# Linear algebra

**Vectorizing** code is the key to writing efficient numerical calculation with Python/Numpy. 

That means that as much as possible of a program should be formulated in terms of matrix and vector operations, like **matrix-matrix multiplication**.

In [53]:
import numpy as np

## Scalar-array operations

We can use the usual arithmetic operators to multiply, add, subtract, and divide arrays with scalar numbers.

In [54]:
v1 = np.arange(0, 5)

In [55]:
v1 * 2

array([0, 2, 4, 6, 8])

In [56]:
v1 + 2

array([2, 3, 4, 5, 6])

In [57]:
A = np.array([[n+m*10 for n in range(5)] for m in range(5)])

In [58]:
print('A * 2: ', '\n', A * 2)
print('A + 2: ', '\n', A + 2)

A * 2:  
 [[ 0  2  4  6  8]
 [20 22 24 26 28]
 [40 42 44 46 48]
 [60 62 64 66 68]
 [80 82 84 86 88]]
A + 2:  
 [[ 2  3  4  5  6]
 [12 13 14 15 16]
 [22 23 24 25 26]
 [32 33 34 35 36]
 [42 43 44 45 46]]


## Element-wise array-array operations

When we add, subtract, multiply and divide arrays with each other, the default behaviour is **element-wise** operations:

In [59]:
A * A # element-wise multiplication

array([[   0,    1,    4,    9,   16],
       [ 100,  121,  144,  169,  196],
       [ 400,  441,  484,  529,  576],
       [ 900,  961, 1024, 1089, 1156],
       [1600, 1681, 1764, 1849, 1936]])

In [60]:
v1 * v1

array([ 0,  1,  4,  9, 16])

If we multiply arrays with compatible shapes, we get an element-wise multiplication of each row:

In [61]:
A.shape, v1.shape

((5, 5), (5,))

In [62]:
A * v1

array([[  0,   1,   4,   9,  16],
       [  0,  11,  24,  39,  56],
       [  0,  21,  44,  69,  96],
       [  0,  31,  64,  99, 136],
       [  0,  41,  84, 129, 176]])

## Matrix algebra

What about **matrix mutiplication**? 

There are two ways. 

We can either use the `np.dot` function, which applies a **matrix-matrix**, **matrix-vector**, or **inner vector multiplication** to its two arguments: 

In [63]:
np.dot(A, A)

array([[ 300,  310,  320,  330,  340],
       [1300, 1360, 1420, 1480, 1540],
       [2300, 2410, 2520, 2630, 2740],
       [3300, 3460, 3620, 3780, 3940],
       [4300, 4510, 4720, 4930, 5140]])

In [64]:
np.dot(A, v1)

array([ 30, 130, 230, 330, 430])

In [65]:
np.dot(v1, v1)

np.int64(30)

## A *new* dedicated Infix operator for Matrix Multiplication

**Python 3.5** (released on the **24th Aug.**) introduces a new binary operator to be used for matrix multiplication, called `@` . (Mnemonic: `@` is * for `mATrices`.)

Some useful hints:

- PEP465 Description: [https://www.python.org/dev/peps/pep-0465/#abstract]()
- [Motivations](https://www.python.org/dev/peps/pep-0465/#motivation)
- [Rationale for Specification Details](https://www.python.org/dev/peps/pep-0465/#rationale-for-specification-details)

---

# Exercises - Linear Algebra

Vectorizing code is the key to writing efficient numerical calculation with Python/Numpy. 

That means that as much as possible of a program should be formulated in terms of matrix and vector operations, like matrix-matrix multiplication.

## Scalar-array operartions

We can use the usual arithmetic operators to multiply, add, subtract, and divide arrays with scalar numbers.

## Ex 4.1 

Generate a matrix of any size. Then multiply each element by `2` and subtract `1`.

#### HInt: The most intuitive way to implement this is the right one!

In [66]:
B = np.random.rand(4, 4)
B = B * 2 - 1
B

array([[ 0.14039354, -0.12279697,  0.97674768, -0.79591038],
       [-0.58224649, -0.67738096,  0.30621665, -0.49341679],
       [-0.06737845, -0.51114882, -0.68206083, -0.77924972],
       [ 0.31265918, -0.7236341 , -0.60683528, -0.26254966]])

## Ex 4.2

Generate two square matrix of random numbers and multiply them element wise.

#### Hint: The clues from the previous exercise also apply here!-)

In [67]:
C1 = np.random.rand(3, 3)
C2 = np.random.rand(3, 3)
C1 * C2

array([[0.03217291, 0.02746092, 0.1007181 ],
       [0.0284586 , 0.1159328 , 0.1490232 ],
       [0.40463597, 0.03879933, 0.51191942]])

## Ex 4.3

Execute the `dot` product between two randomly generated matrix of comparable shapes.

#### Hint: Since we are using Python 3 here, you should be aware of the `@` operator.. :)

In [68]:
D1 = np.random.rand(3, 4)
D2 = np.random.rand(4, 3)
D1 @ D2

array([[0.77237857, 0.75035836, 0.72525314],
       [0.96090693, 1.34313153, 1.18951438],
       [0.39898132, 0.87510875, 0.47948886]])

## Ex 4.4

Generate a matrix of any size and create the transpose.

#### Hint: Guess the difference from `np.transpose` and `array.T`

In [69]:
E = np.random.rand(3, 5)
print(np.transpose(E))
print(E.T)

[[0.22308163 0.29743695 0.88173536]
 [0.95274901 0.81379782 0.69253159]
 [0.44712538 0.39650574 0.72525428]
 [0.84640867 0.8811032  0.50132438]
 [0.69947928 0.58127287 0.95608363]]
[[0.22308163 0.29743695 0.88173536]
 [0.95274901 0.81379782 0.69253159]
 [0.44712538 0.39650574 0.72525428]
 [0.84640867 0.8811032  0.50132438]
 [0.69947928 0.58127287 0.95608363]]


## Ex 4.5

Generate a `ndarray` of any size and shape of random numbers and calculate some statistics (`mean`, `sum` along axis, `min`, `max`)


#### HInt: Clues in the text of the exercise !-)

In [70]:
F = np.random.rand(4, 5)
print('mean:', F.mean())
print('sum along axis 0:', F.sum(axis=0))
print('sum along axis 1:', F.sum(axis=1))
print('min:', F.min())
print('max:', F.max())

mean: 0.4798828489491121
sum along axis 0: [2.25454933 1.715316   2.711828   1.38984902 1.52611463]
sum along axis 1: [1.99500648 2.13250934 2.68664607 2.7834951 ]
min: 0.019193198309333526
max: 0.896546595851063


---

# Indexing

### Setting up the data

In [71]:
np.random.seed(42)  # Setting the random seed

In [72]:
# a vector: the argument to the array function is a Python list
v = np.random.rand(10)
v

array([0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864,
       0.15599452, 0.05808361, 0.86617615, 0.60111501, 0.70807258])

In [73]:
# a matrix: the argument to the array function is a nested Python list
M = np.random.rand(10, 2)
M

array([[0.02058449, 0.96990985],
       [0.83244264, 0.21233911],
       [0.18182497, 0.18340451],
       [0.30424224, 0.52475643],
       [0.43194502, 0.29122914],
       [0.61185289, 0.13949386],
       [0.29214465, 0.36636184],
       [0.45606998, 0.78517596],
       [0.19967378, 0.51423444],
       [0.59241457, 0.04645041]])

We can index elements in an array using the square bracket and indices:

In [74]:
# v is a vector, and has only one dimension, taking one index
v[0]

np.float64(0.3745401188473625)

In [75]:
# M is a matrix, or a 2 dimensional array, taking two indices 
M[1,1]

np.float64(0.21233911067827616)

If we omit an index of a multidimensional array it returns the whole row (or, in general, a N-1 dimensional array) 

In [76]:
M[1] 

array([0.83244264, 0.21233911])

The same thing can be achieved with using `:` instead of an index: 

In [77]:
M[1,:] # row 1

array([0.83244264, 0.21233911])

In [78]:
M[:,1] # column 1

array([0.96990985, 0.21233911, 0.18340451, 0.52475643, 0.29122914,
       0.13949386, 0.36636184, 0.78517596, 0.51423444, 0.04645041])

We can assign new values to elements in an array using indexing:

In [79]:
M[0,0] = 1

In [80]:
M

array([[1.        , 0.96990985],
       [0.83244264, 0.21233911],
       [0.18182497, 0.18340451],
       [0.30424224, 0.52475643],
       [0.43194502, 0.29122914],
       [0.61185289, 0.13949386],
       [0.29214465, 0.36636184],
       [0.45606998, 0.78517596],
       [0.19967378, 0.51423444],
       [0.59241457, 0.04645041]])

In [81]:
# also works for rows and columns
M[1,:] = 0
M[:,1] = -1

In [82]:
M

array([[ 1.        , -1.        ],
       [ 0.        , -1.        ],
       [ 0.18182497, -1.        ],
       [ 0.30424224, -1.        ],
       [ 0.43194502, -1.        ],
       [ 0.61185289, -1.        ],
       [ 0.29214465, -1.        ],
       [ 0.45606998, -1.        ],
       [ 0.19967378, -1.        ],
       [ 0.59241457, -1.        ]])

## Index slicing

Index slicing is the technical name for the syntax `M[lower:upper:step]` to extract part of an array:

In [83]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [84]:
a[1:3]

array([2, 3])

Array slices are **mutable**: if they are assigned a new value the original array from which the slice was extracted is modified:

In [85]:
a[1:3] = [-2,-3]

a

array([ 1, -2, -3,  4,  5])

* We can omit any of the three parameters in `M[lower:upper:step]`:

In [86]:
a[::] # lower, upper, step all take the default values

array([ 1, -2, -3,  4,  5])

In [87]:
a[::2] # step is 2, lower and upper defaults to the beginning and end of the array

array([ 1, -3,  5])

In [88]:
a[:3] # first three elements

array([ 1, -2, -3])

In [89]:
a[3:] # elements from index 3

array([4, 5])

* Negative indices counts from the end of the array (positive index from the begining):

In [90]:
a = np.array([1,2,3,4,5])

In [91]:
a[-1] # the last element in the array

np.int64(5)

In [92]:
a[-3:] # the last three elements

array([3, 4, 5])

* Index slicing works exactly the same way for multidimensional arrays:

In [93]:
A = np.array([[n+m*10 for n in range(5)] 
              for m in range(5)])
A

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34],
       [40, 41, 42, 43, 44]])

In [94]:
# a block from the original array
A[1:4, 1:4]

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [95]:
# strides
A[::2, ::2]

array([[ 0,  2,  4],
       [20, 22, 24],
       [40, 42, 44]])

## Fancy indexing

Fancy indexing is the name for when an array or list is used in-place of an index: 

In [96]:
row_indices = [1, 2, 3]
A[row_indices]

array([[10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34]])

In [97]:
col_indices = [1, 2, -1] # remember, index -1 means the last element
A[row_indices, col_indices]

array([11, 22, 34])

* We can also index **masks**: 

    - If the index mask is an Numpy array of with data type `bool`, then an element is selected (True) or not (False) depending on the value of the index mask at the position each element: 

In [98]:
b = np.array([n for n in range(5)])
b

array([0, 1, 2, 3, 4])

In [99]:
row_mask = np.array([True, False, True, False, False])
b[row_mask]

array([0, 2])

* Alternatively:

In [101]:
# same thing
row_mask = np.array([1,0,1,0,0], dtype=bool)
b[row_mask]

array([0, 2])

This feature is very useful to conditionally select elements from an array, using for example comparison operators:

In [102]:
x = np.arange(0, 10, 0.5)
x

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

In [103]:
mask = (5 < x) * (x < 7.5)

mask

array([False, False, False, False, False, False, False, False, False,
       False, False,  True,  True,  True,  True, False, False, False,
       False, False])

In [104]:
x[mask]

array([5.5, 6. , 6.5, 7. ])

Alternatively, we can use the condition (mask) array directly within brackets to index the array

In [105]:
x[(5 < x) * (x < 7.5)]

array([5.5, 6. , 6.5, 7. ])

---

# Exercises on Indexing

Index slicing is the technical name for the syntax `M[lower:upper:step]` to extract part of an array

## Ex 3.1 

Generate a three-dimensional array of any size containing random numbers taken from an uniform distribution (_guess the numpy function in `np.random`_). Then print out separately the first entry along the three axis (i.e. `x, y, z`)  


#### Hint: Slicing with numpy arrays works quite like Python lists

In [106]:
G = np.random.uniform(size=(4, 5, 6))
print(G[0])        # first entry along the x axis
print(G[:, 0])      # first entry along the y axis
print(G[:, :, 0])   # first entry along the z axis

[[0.60754485 0.17052412 0.06505159 0.94888554 0.96563203 0.80839735]
 [0.30461377 0.09767211 0.68423303 0.44015249 0.12203823 0.49517691]
 [0.03438852 0.9093204  0.25877998 0.66252228 0.31171108 0.52006802]
 [0.54671028 0.18485446 0.96958463 0.77513282 0.93949894 0.89482735]
 [0.59789998 0.92187424 0.0884925  0.19598286 0.04522729 0.32533033]]
[[0.60754485 0.17052412 0.06505159 0.94888554 0.96563203 0.80839735]
 [0.38867729 0.27134903 0.82873751 0.35675333 0.28093451 0.54269608]
 [0.11959425 0.71324479 0.76078505 0.5612772  0.77096718 0.4937956 ]
 [0.80744016 0.8960913  0.31800347 0.11005192 0.22793516 0.42710779]]
[[0.60754485 0.30461377 0.03438852 0.54671028 0.59789998]
 [0.38867729 0.14092422 0.00552212 0.35846573 0.31098232]
 [0.11959425 0.52273283 0.31435598 0.22879817 0.63340376]
 [0.80744016 0.81801477 0.11986537 0.3636296  0.28484049]]


## Ex 3.2

Create a vector and print out elements in reverse order

#### Hint: Use slicing for this exercise

In [107]:
H = np.arange(10)
print(H[::-1])

[9 8 7 6 5 4 3 2 1 0]


## Ex 3.3

Generate a $7 \times 7$ matrix and replace all the elements in odd rows and even columns with `1`.

#### Hint: Use slicing to solve this exercise!

#### Note: Take a look at the original matrix, then.

In [108]:
I = np.arange(49).reshape(7, 7)
print('Original:\n', I)

# odd rows (index 1, 3, 5, ...) and even columns (index 0, 2, 4, 6, ...)
I[1::2, ::2] = 1
print('Modified:\n', I)

Original:
 [[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34]
 [35 36 37 38 39 40 41]
 [42 43 44 45 46 47 48]]
Modified:
 [[ 0  1  2  3  4  5  6]
 [ 1  8  1 10  1 12  1]
 [14 15 16 17 18 19 20]
 [ 1 22  1 24  1 26  1]
 [28 29 30 31 32 33 34]
 [ 1 36  1 38  1 40  1]
 [42 43 44 45 46 47 48]]


## Ex 3.4 

Generate a `10 x 10` matrix of numbers `A`. Then, generate a numpy array of integers in range `1-9`. Pick `5` random values (with no repetition) from this array and use these values to extract rows from the original matrix `A`.

In [109]:
A10 = np.arange(100).reshape(10, 10)
idx_pool = np.arange(1, 10)
chosen_rows = np.random.choice(idx_pool, size=5, replace=False)
print('chosen rows:', chosen_rows)
A10[chosen_rows]

chosen rows: [4 7 5 8 2]


array([[40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

## Ex 3.5 

Repeat the previous exercise but this time extract columns from `A`

In [110]:
chosen_cols = np.random.choice(idx_pool, size=5, replace=False)
print('chosen cols:', chosen_cols)
A10[:, chosen_cols]

chosen cols: [2 1 5 9 3]


array([[ 2,  1,  5,  9,  3],
       [12, 11, 15, 19, 13],
       [22, 21, 25, 29, 23],
       [32, 31, 35, 39, 33],
       [42, 41, 45, 49, 43],
       [52, 51, 55, 59, 53],
       [62, 61, 65, 69, 63],
       [72, 71, 75, 79, 73],
       [82, 81, 85, 89, 83],
       [92, 91, 95, 99, 93]])

## Ex 3.6

Generate an array of numbers from `0` to `20` with step `0.5`. 
Extract all the values greater than a randomly generated number in the same range.

#### Hint: Try to write the condition as an expression and save it to a variable. Then, use this variable in square brackets to index.... this is when the magic happens!

In [111]:
J = np.arange(0, 20.5, 0.5)
random_number = np.random.uniform(0, 20)
print('random number:', random_number)

mask = J > random_number
J[mask]

random number: 14.564326972237192


array([15. , 15.5, 16. , 16.5, 17. , 17.5, 18. , 18.5, 19. , 19.5, 20. ])